"""database add qr

Revision ID: aed804bd2a0e
Revises: ea93af59ee92
Create Date: 2023-05-22 14:53:55.695122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed804bd2a0e'
down_revision = 'ea93af59ee92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_password',
    sa.Column('pasword_hash', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_constraint('queue_ibfk_4', 'queue', type_='foreignkey')
    op.create_foreign_key(None, 'queue', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.create_foreign_key('queue_ibfk_4', 'queue', 'car', ['car_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_table('user_password')
    op.drop_table('user_account')
    op.drop_table('qr_table')
    # ### end Alembic commands ###
